version: 0.2

phases:

  install:
    runtime-versions:
      java: latest

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION
      - echo AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID
      - echo IMAGE_REPO_NAME = $IMAGE_REPO_NAME
      - echo IMAGE_TAG = $IMAGE_TAG
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building application...
      - mvn -ntp install
      - echo Building the Docker image...
      - sudo docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - sudo docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/scraper-frontend-0.0.1.jar